name: CI

on:
  push:
    tags: [ "v*" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CD_REPO: leandrosouzabc/app-deployments-ops
  CD_REPO_PATH: app-deployments-ops
  CD_FILE_TO_CHANGE_TAG: demo-spring-boot-gradle/overlays/dev/kustomization.yaml

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test

  build-and-push-image:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  update-cd-repo:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitOps Repo
      uses: actions/checkout@v3
      with:
        repository: ${{ env.CD_REPO }}
        path: ${{ env.CD_REPO_PATH }}
    - run: |
        pwd
        sed -i 's/v.*.*.*/${{ github.ref_name }}/g'./${{ env.CD_REPO_PATH }}/${{ env.CD_FILE_TO_CHANGE_TAG }}
        git config user.name ${{ secrets.BOT_USER_NAME }}
        git config user.email ${{ secrets.BOT_USER_EMAIL }}
        git add .
        git commit -m "generated"
        git push       